### ISSUE TITLE
parse_remote_state regex issue

### ISSUE THREAD

**Issue by mikesigs** [jondavidjohn/dotfiles#1]
I'm trying to get your .bashrc working on Ubuntu 14.10. The regexes on the following lines don't appear to be working: https://github.com/jondavidjohn/dotfiles/blob/master/general/.bash_profile#L135-L136

I've changed them to use perl lookaheads and they now work great. Just thought I'd let you know. I'm a bash noob so perhaps you can enlighten me.

```sh
behind_num=$(echo "$remote_state" | grep -Poh "(?<=behind )\d*")
ahead_num=$(echo "$remote_state" | grep -Poh "(?<=ahead )\d*")
```

I use the same code on lines 142 and 139 respectively.

**Comment by jondavidjohn** [comment]
Interesting, thanks for the heads up. :100:
